name: Deploy React App

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.jsx'
      - '**.css'
      - '**.html'
      - 'public/**'
      - 'src/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy.outputs.website-url }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server (example with SSH)
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /path/to/your/project
          git pull origin main
          npm install --production
          pm2 restart app
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to Netlify (example)
      run: |
        curl -X POST -d '{"branch": "main"}' https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK }}

